### ISSUE TITLE
Blocked Requesters/HITs resetting upon refresh.

### ISSUE THREAD

**Issue by CrumpThePenguin** [Anveio/mturk-engine#6] opened 2017-10-19 02:32 UTC
All blocked HITs/Requesters completely reset upon refresh. I'm not sure if this is an issue with MTURK Engine as much as it is a MTURK or browser issue.

**Comment by Anveio** [comment] 2017-10-19 06:00
Hi @CrumpThePenguin thanks for submitting this issue. It's most likely an Mturk Engine issue but it's difficult to know for sure because I've had no luck reproducing it. If you'd like to help me with this: when you switch to the Blocklist tab, do any errors show up in the console? (You can open the console with F12.)

I can look into this more tomorrow but I probably won't be able to fix the underlying cause until a major release, which I have no ETA for. In the meantime, if you're willing to part with **ALL** of  your saved Mturk Engine data, look into a _possible_ solution I posted about here: https://github.com/Anveio/mturk-engine/issues/4

**Comment by Anveio** [comment] 2018-02-01 19:24
Doing some spring cleaning. I'm assuming this was caused by watcher's not being read from browser storage properly, causing the crash. This was fixed in 1.3.0, I believe, so I'm closing this for now. If the issue shows up again, feel free to post a new issue and I'll look at it.

**Closed by Anveio** 2018-02-01 19:24 UTC
