### ISSUE TITLE
Keeps deleting my blocked requesters?

### ISSUE THREAD

**Issue by lisbethchaos** [Anveio/mturk-engine#3] opened 2017-09-23 23:32 UTC
Hi there! Love the script. I'm running it in Chrome, but I've had the same issue running it in Firefox. I can click on "add requester to blocklist" and it's filtered out, but I'm unable to click on the blocklist. When I reload the script page, sometimes it will show all the requesters I've blocked and sometimes it shows nothing--just shows the main screen, won't let me search, won't let me click on any tabs.

Any idea what could be behind this?

**Comment by Anveio** [comment] 2017-09-24 17:20
Hi @lisbethchaos thanks for submitting this issue (and for submitting the first issue for this project!). 

It sounds to me like blocking a requester is causing the application to crash. I'll need more information to pin down exactly what's causing that, though, because I'm unable to reproduce the bug. If you'd like to help me out with this: when Mturk Engine stops working, open the console with Control + Shift + I (or F12) and copy the error messages you see there and paste it in this thread.

**Comment by lisbethchaos** [comment] 2017-09-24 21:47
Thanks for getting back to me!

I tried deleting everyone on my blocklist, uninstalling and reinstalling the script, tried the lite version, made sure that all other scripts (IE Ghostery) were disabled. It also won't show my watchers--I can search and click on "add as watcher", but when I try to click over to the watcher tab, one of the attached photos happens.

![screen shot 2017-09-24 at 5 34 11 pm](https://user-images.githubusercontent.com/32230734/30787124-09e864c4-a150-11e7-8205-adba26f919c3.png)

That's what my screen looks like on a 'normal' load, even after deleting all blocked HITS/requesters.

![screen shot 2017-09-24 at 5 37 44 pm](https://user-images.githubusercontent.com/32230734/30787129-2912f076-a150-11e7-9cb2-636e7726bac1.png)

That's what my screen looks like if I have no other scripts enabled, click on the settings tab, then refresh the page.

![screen shot 2017-09-24 at 5 41 52 pm](https://user-images.githubusercontent.com/32230734/30787134-44f3acae-a150-11e7-9875-df7383ad3314.png)

And finally, that's the error message I see when I try to click on the "watchers" tab.

**Comment by Anveio** [comment] 2017-09-25 00:56
I have to admit I'm stumped as to what initially could have caused this. My initial guess is something corrupted the data that Mturk Engine uses to persist your blocklist and watchers through page reloads/installs. But you mentioned that you're having this issue on more than one browser, which makes me unsure if that's really the problem.

If it is, and you're willing to delete all of Mturk Engine's stored data, open the console again and paste in this command, then press enter.

`window.indexedDB.deleteDatabase('localforage')`

To be clear, this command will revert Mturk Engine to its default (empty) state and delete any changes you've made. If you decide to do it, let me know if that fixed your problem.

**Comment by lisbethchaos** [comment] 2017-09-25 12:04
![screen shot 2017-09-25 at 8 01 26 am](https://user-images.githubusercontent.com/32230734/30807447-dda91f0c-a1c7-11e7-8abf-e6834c826ded.png)

It looks like--knock on wood--that solved it? I'm able to add watchers now and reload the page without issue. Thanks for trouble-shooting for me!

**Comment by Anveio** [comment] 2017-09-25 17:33
I'm glad you were able to get the issue fixed. I'll close this issue and chalk this up to random data corruption but if you run into this problem again feel free to open another issue.

**Closed by Anveio** 2017-09-25 17:33 UTC
