### ISSUE TITLE
MTURK Engine breaking after short use

### ISSUE THREAD

**Issue by CrumpThePenguin** [Anveio/mturk-engine#7] opened 2017-10-24 18:48 UTC
# Issue summary
-  As of today, MTURK engine will occasionally break after a very short period of time. The page will show text from the element I attempted to click (e.g. "Adding to queue") with a small bar under the text. After a few more seconds the page goes completely white, requiring a refresh.

## Expected behavior

-  MTURK engine typically would allow me to use it without breaking. Adding HITs to queue, watchers, etc. Basically all the normal functionality of the program.

## Actual behavior

- Page displays an element of text somewhat relevant to what MTURK engine was doing at the time ("Adding to queue", "Adding watcher", etc.)

## Steps to Reproduce the Problem

- I haven't been able to find a way to reliably reproduce the problem. It sometimes happens after 30 minutes of use, and sometimes immediately after refresh.

## Specifications

- Mturk Engine version: 1.3.2
- Are you using the Lite version? : No
- Browser: Firefox

**Comment by CrumpThePenguin** [comment] 2017-10-24 18:53
![image](https://user-images.githubusercontent.com/24972809/31962239-aad5d702-b8c2-11e7-82f0-cbf66ba8c866.png)
Here's a screenshot of the described problem.

**Comment by Anveio** [comment] 2018-02-01 19:24
Doing some spring cleaning. I'm assuming this was caused by watcher's not being read from browser storage properly, causing the crash. This was fixed in 1.3.0, I believe, so I'm closing this for now. If the issue shows up again, feel free to post a new issue and I'll look at it.

**Closed by Anveio** 2018-02-01 19:24 UTC
