### ISSUE TITLE
Can't click on Search, Queue or Watchers

### ISSUE THREAD

**Issue by CaliGirl28** [Anveio/mturk-engine#4] opened 2017-09-26 23:38 UTC
I was using Mturk Engine for an hour or two this morning with no issues. All of a sudden as I tried to delete a couple of Watchers it locked up and I couldn't click on anything. It hasn't worked for several hours. I've tried refreshing and restarting my computer and I can't get past the "Start Searching" screen. I'm experiencing this issue in the Chrome Browser on a Windows 10 machine.

**Comment by Anveio** [comment] 2017-09-27 02:21
Hi @CaliGirl28, thanks for submitting this issue. Another user also reported a similar issue with the Watchers tab causing the application to crash. I'm unable to track down the exact cause of this bug or a satisfactory solution right now but if you want a last resort solution I may have one.

To be clear: **this will reset Mturk Engine to factory settings and delete all of your data (notably your blocked HITs and requesters).**

While on the Mturk Engine home paged (crashed or not), open the console with CTRL + SHIFT + I (or F12) and paste in this command:

`window.indexedDB.deleteDatabase('localforage')`

To reiterate, this will delete all of your data. If you decide to do it, I hope it works for you. Sorry I can't give you a better solution right now but I'm working hard on the next update which will hopefully have a fix for this nasty bug.

**Comment by CaliGirl28** [comment] 2017-09-28 05:11
Thanks for your reply. I was able to get it working again but clearing my browsing history. As expected, I lost all of my data but it is working again for me.

**Comment by Anveio** [comment] 2018-02-01 19:24
Doing some spring cleaning. I'm assuming this was caused by watcher's not being read from browser storage properly, causing the crash. This was fixed in 1.3.0, I believe, so I'm closing this for now. If the issue shows up again, feel free to post a new issue and I'll look at it.

**Closed by Anveio** 2018-02-01 19:24 UTC
